### ISSUE TITLE
Don't assume GET Statements by current registration

### ISSUE THREAD

**Issue by garemoko** [RusticiSoftware/TinCanJS#118]
Currently if the TinCan object has a registration property (e.g. from the querystring) there is no way to GET statements without filtering by that registration. 

I propose we delete these lines: https://github.com/RusticiSoftware/TinCanJS/blob/master/src/TinCan.js#L773-L775

**Comment by brianjmiller** [comment]
That would be a pretty significant backwards compatibility issue, particularly for launch based APs. 

Frankly the whole `TinCan` interface is likely to go away preferring instead to implement directly against the `TinCan.LRS` interface which is the best approach here anyways. 

A better interim fix would be to allow passing `null` as a value for a parameter to that method, then in the query builder in `TinCan.LRS` we could skip anything with a `null` value.

**Comment by garemoko** [comment]
It's actually already possible to pass a null value to TinCan.getStatements - you just get an error from the LRS because null is an invalid value for registration. I believe the PR above should stop the null value being passed through.

**Comment by garemoko** [comment]
This should be fixed in the next build. (see #119)

**Comment by brianjmiller** [comment]
Available in 0.40.0.
