### ISSUE TITLE
Create a Meteor module

### ISSUE THREAD

**Issue by paulo2nd** [RusticiSoftware/TinCanJS#123]
Could you create a meteor module and publish into atmospherejs? This would help a lot :)

**Comment by brianjmiller** [comment]
Based on an admittedly small amount of research it looks like you should be able to pull in normal npm modules for use in meteor (see https://themeteorchef.com/snippets/using-npm-packages/). We have very limited time to spend on development of the library and no way to test that type of distribution so I'd rather not add another package management solution, I already want to get rid of bower as it is.

**Comment by vincentracine** [comment]
@brianjmiller Yes you are correct. As of Meteor 1.3, NPM packages can be used directly.
