### ISSUE TITLE
StatementsResult.more Property

### ISSUE THREAD

**Issue by messyhair66** [RusticiSoftware/TinCanJS#135]
In [this example](http://rusticisoftware.github.io/TinCanJS/#retrieving-statements), it appears you can check .more for null to determine if additional data is available to fetch. I observe a different behavior: the .more property always has a value set regardless if additional data is available. Console log capture [here](https://i.imgur.com/LvJfG9i.png). I am querying against a saas.learninglocker.net organization.

I don't know if this is an err in documentation, API, or my own mistake. I appreciate any feedback.

**Comment by garemoko** [comment]
The more property is optional in that scenario so depending on the LRS could either be not present or an empty string. For interoperbility you'll need to account for both possibilities.

**Comment by messyhair66** [comment]
Thank you! Closing issue.
