### ISSUE TITLE
Unable to capture Drupal Node Alias path

### ISSUE THREAD

**Issue by ghost** [RusticiSoftware/TinCanJS#136]
When I open a node in drupal and it uses an Alias path the statement is generated with the node path not the alias path.

This means I cannot map it back to the alias path 

eg.
Alias Path
http://www.xxx.com/training/?q=flashbrand/elevator-pitch
Node Path
http://www.xxx.com/training/?q=node/63

Is there a way to force tincan api to capture the path being used (the alias path) rather than the node path?

**Comment by garemoko** [comment]
Can you post your code that's fetching the path? And maybe include a screenshot of the user's view?

Also, if you're using Drupal, you might want to consider TinCanPHP instead of TinCanJS.
