### ISSUE TITLE
Return value from Statement() is not a valid xAPI statement

### ISSUE THREAD

**Issue by Vitzkrieg** [RusticiSoftware/TinCanJS#143]
I am using the Node.js package and when creating a statement using TinCan.Statement({mypropsobj}), the resulting statement object is not valid. It contains 'target' instead of 'object' other custom properties.

Is there a function to get a valid statement back without these other properties?

I already created a cleanup function for this using lodash - plain JS, jQuery, or other lib could be substituted easily enough, but it would be nice to not have this extra code if possible.

```

    //remove empty values from object
    static cleanupStatement(data: any): any {

        if (data && data.actor && data.verb && data.target) {
            data.object = _.clone(data.target);
            data.target = null;
        }
        
        _.forIn(data, function(value: any, key: string) {
            if (key === "LOG_SRC" || key === "degraded" || value === "" || value === null) {
                delete data[key];
            } else
             if (!_.isNumber(value) && !_.isString(value) && !_.isBoolean(value)) {
                ExperienceAPI.cleanupStatement(value);
                if ((_.isArray(value) || _.isObject(value)) && _.isEmpty(value)) {
                    delete data[key];
                }
            }
        });

        return data;
    }
```

**Comment by Vitzkrieg** [comment]
The main reason for this is to validate the statement before sending to the LRS to avoid unnecessary server calls and possible user feedback and/or logging.

**Comment by garemoko** [comment]
Take a look at the asVersion method: https://github.com/RusticiSoftware/TinCanJS/blob/8733f14ddcaeea77a0579505300bc8f38921a6b1/src/Statement.js#L328

**Comment by brianjmiller** [comment]
As @garemoko pointed out you should use the `asVersion` to get a proper serialized object for the version you seek. Having said that, there is very little "validation" logic in the library, on purpose mostly, so it is still possible to get a non-valid statement from a call to `asVersion`. The library *may* at some point in a new major version get the capability to do validation, but that will significantly change the public interface to require the use of getters/setters (or some sort of property change event handling or similar) (see the roadmap: https://github.com/RusticiSoftware/TinCanJS/issues/110).

If you absolutely want to do library side validation I'd suggest integrating with the JSON schema available at https://github.com/RusticiSoftware/TinCanSchema and you may want to have a look at the corresponding validator https://github.com/RusticiSoftware/TinCanValidator .
