### ISSUE TITLE
Tracking logs of scorm file

### ISSUE THREAD

**Issue by Mustufask** [RusticiSoftware/TinCanJS#162]
Dear @brianjmiller  Sir,

I hope this message finds you well. I'm reaching out with a query regarding your expertise with SCORM (Sharable Content Object Reference Model). Specifically, we have a SCORM zip file and are interested in tracking logs when this file is played. Could you kindly provide guidance on how to retrieve these logs programmatically?

Additionally, we are curious about the possibility of creating our own Learning Record Store (LRS) using ReactJS. Is it feasible to implement an LRS using this technology stack? If so, could you outline the steps or methods involved in integrating it with our application?

Your insights and expertise would be greatly appreciated. Looking forward to your guidance on these matters.

Best regards,  
Mustufa shaikh 
mustufask54@gmail.com

**Comment by brianjmiller** [comment]
If you still need assistance please reach out to support@rusticisoftware.com. Closing this as off topic for TinCanJS.
