### ISSUE TITLE
Handle slightly incorrect inputs

### ISSUE THREAD

**Issue by garemoko** [RusticiSoftware/TinCanJS#38]
The js library should be able to handle:

* LRS endpoints that lack the final /
* mbox values that lack the initial "mailto:" (this is already handled if the mailbox is set when the actor is created, but not if the property is defined later e.g. on the next line. For use case, see https://github.com/garemoko/tinStatement/blob/cdbcc0bce1f3b0d7c97bfc3d0bdd2a5e0fc5a623/TinStatement.js#L135)

**Comment by brianjmiller** [comment]
Closing as I think the remaining request of using a get/set model is captured by the roadmap #110.
