### ISSUE TITLE
Implement Document API Merge

### ISSUE THREAD

**Issue by davidells** [RusticiSoftware/TinCanJS#71]
See https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#json-procedure-with-requirements

The spec allows you to POST json, and if you do so, the existing contents are merged with whatever is posted (or conflicting fields are overwritten). Since many use cases will utilitize JSON for the document value, this is another way to avoid the heavy lifting of get / set with the ETag. Plus, there are probably some less likely use cases that actually want to utilize the merging semantics themselves.

**Comment by brianjmiller** [comment]
@garemoko did #97 take care of this?

**Comment by garemoko** [comment]
Yes, this is exactly the issue that #97 was designed to resolve (without knowing this Issue existed)
